### PR TITLE
We're actually going to use 132 for the last token

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Marker 131 turns out not to be recognisable by libkoki, even given a pristine image. I suspect this is due to the locations of the squares in the marker, but haven't investigated deeply.

### CODE REVIEW

**Comment by TomWheal** [comment]
This can be disregarded now right?

**Comment by RealOrangeOne** [comment]
Assuming we shipped this at SR2019, it'd be nice to get this merged for historical reasons.

**Review by TomWheal — APPROVED** [review]
Approving this for historic reasons

**Review by RealOrangeOne — APPROVED** [review]

**Review by kierdavis — APPROVED** [review]

**Comment by PeterJCLaw** [comment]
I can't actually remember what we did, though I think we must have done this.

**Pull request merged**
